export const defaultBBcodeStr = `[center][h1]Big text that can be [b]Bold[/b][/h1][/center]
[right]Nope, not bold, [u]but underlined[/u][/right]
[ul][li]Test[/li]
[center][li]Oh yeah[/li][/center]
[right][li]That's nice[/li][/right]
[/ul]
[ol][right][li]Now we have [color=FF0000]something[/color] to work with[/li][/right]
[center][li]Yep[/li][/center]
[li]And autocorrrect[/li]
[/ol]
[h2]This looks like a success in the making[/h2]`;
